server:
  port: 9003
spring:
  application:
    name: dubbo3-provider

dubbo:
  application:
    name: dubbo3-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    serialization: protobuf
    port: 20881
